# Generated by Django 4.0.3 on 2022-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=50, verbose_name='заказ №')),
                ('price_usd', models.CharField(max_length=50, verbose_name='стоимость $')),
                ('price_rub', models.CharField(max_length=50, verbose_name='стоимость руб')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='время поставки')),
            ],
        ),
    ]
