# Generated by Django 4.0.3 on 2022-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(max_length=50, verbose_name='срок поставки'),
        ),
    ]
